# development:
#   adapter: mysql2
#   host: localhost
#   database: wmp_development
#   username: root
#   encoding: utf8

development:
  adapter: postgresql
  encoding: unicode
  database: donations_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: donations_prod
  pool: 5
  timeout: 5000